// AUTO-GENERATED country reference data (ISO 3166-1).
// Maps a visitor country (ISO alpha-2, from the x-vercel-ip-country header) to a
// display name and the ISO 3166-1 numeric code used by the world-atlas TopoJSON
// (leading zeros stripped, e.g. "004" -> "4"), so map regions can be matched to
// analytics counts. Do not edit by hand — regenerate from the ISO 3166 dataset.

export interface CountryInfo {
  name: string;
  /** ISO 3166-1 numeric code (no leading zeros) — matches world-atlas feature ids. */
  numeric: string;
}

/** Keyed by uppercase ISO alpha-2 code. */
export const COUNTRIES: Record<string, CountryInfo> = {
  AD: { name: "Andorra", numeric: "20" },
  AE: { name: "United Arab Emirates", numeric: "784" },
  AF: { name: "Afghanistan", numeric: "4" },
  AG: { name: "Antigua and Barbuda", numeric: "28" },
  AI: { name: "Anguilla", numeric: "660" },
  AL: { name: "Albania", numeric: "8" },
  AM: { name: "Armenia", numeric: "51" },
  AO: { name: "Angola", numeric: "24" },
  AQ: { name: "Antarctica", numeric: "10" },
  AR: { name: "Argentina", numeric: "32" },
  AS: { name: "American Samoa", numeric: "16" },
  AT: { name: "Austria", numeric: "40" },
  AU: { name: "Australia", numeric: "36" },
  AW: { name: "Aruba", numeric: "533" },
  AX: { name: "Åland Islands", numeric: "248" },
  AZ: { name: "Azerbaijan", numeric: "31" },
  BA: { name: "Bosnia and Herzegovina", numeric: "70" },
  BB: { name: "Barbados", numeric: "52" },
  BD: { name: "Bangladesh", numeric: "50" },
  BE: { name: "Belgium", numeric: "56" },
  BF: { name: "Burkina Faso", numeric: "854" },
  BG: { name: "Bulgaria", numeric: "100" },
  BH: { name: "Bahrain", numeric: "48" },
  BI: { name: "Burundi", numeric: "108" },
  BJ: { name: "Benin", numeric: "204" },
  BL: { name: "Saint Barthélemy", numeric: "652" },
  BM: { name: "Bermuda", numeric: "60" },
  BN: { name: "Brunei Darussalam", numeric: "96" },
  BO: { name: "Bolivia, Plurinational State of", numeric: "68" },
  BQ: { name: "Bonaire, Sint Eustatius and Saba", numeric: "535" },
  BR: { name: "Brazil", numeric: "76" },
  BS: { name: "Bahamas", numeric: "44" },
  BT: { name: "Bhutan", numeric: "64" },
  BV: { name: "Bouvet Island", numeric: "74" },
  BW: { name: "Botswana", numeric: "72" },
  BY: { name: "Belarus", numeric: "112" },
  BZ: { name: "Belize", numeric: "84" },
  CA: { name: "Canada", numeric: "124" },
  CC: { name: "Cocos (Keeling) Islands", numeric: "166" },
  CD: { name: "Congo, Democratic Republic of the", numeric: "180" },
  CF: { name: "Central African Republic", numeric: "140" },
  CG: { name: "Congo", numeric: "178" },
  CH: { name: "Switzerland", numeric: "756" },
  CI: { name: "Côte d'Ivoire", numeric: "384" },
  CK: { name: "Cook Islands", numeric: "184" },
  CL: { name: "Chile", numeric: "152" },
  CM: { name: "Cameroon", numeric: "120" },
  CN: { name: "China", numeric: "156" },
  CO: { name: "Colombia", numeric: "170" },
  CR: { name: "Costa Rica", numeric: "188" },
  CU: { name: "Cuba", numeric: "192" },
  CV: { name: "Cabo Verde", numeric: "132" },
  CW: { name: "Curaçao", numeric: "531" },
  CX: { name: "Christmas Island", numeric: "162" },
  CY: { name: "Cyprus", numeric: "196" },
  CZ: { name: "Czechia", numeric: "203" },
  DE: { name: "Germany", numeric: "276" },
  DJ: { name: "Djibouti", numeric: "262" },
  DK: { name: "Denmark", numeric: "208" },
  DM: { name: "Dominica", numeric: "212" },
  DO: { name: "Dominican Republic", numeric: "214" },
  DZ: { name: "Algeria", numeric: "12" },
  EC: { name: "Ecuador", numeric: "218" },
  EE: { name: "Estonia", numeric: "233" },
  EG: { name: "Egypt", numeric: "818" },
  EH: { name: "Western Sahara", numeric: "732" },
  ER: { name: "Eritrea", numeric: "232" },
  ES: { name: "Spain", numeric: "724" },
  ET: { name: "Ethiopia", numeric: "231" },
  FI: { name: "Finland", numeric: "246" },
  FJ: { name: "Fiji", numeric: "242" },
  FK: { name: "Falkland Islands (Malvinas)", numeric: "238" },
  FM: { name: "Micronesia, Federated States of", numeric: "583" },
  FO: { name: "Faroe Islands", numeric: "234" },
  FR: { name: "France", numeric: "250" },
  GA: { name: "Gabon", numeric: "266" },
  GB: {
    name: "United Kingdom of Great Britain and Northern Ireland",
    numeric: "826",
  },
  GD: { name: "Grenada", numeric: "308" },
  GE: { name: "Georgia", numeric: "268" },
  GF: { name: "French Guiana", numeric: "254" },
  GG: { name: "Guernsey", numeric: "831" },
  GH: { name: "Ghana", numeric: "288" },
  GI: { name: "Gibraltar", numeric: "292" },
  GL: { name: "Greenland", numeric: "304" },
  GM: { name: "Gambia", numeric: "270" },
  GN: { name: "Guinea", numeric: "324" },
  GP: { name: "Guadeloupe", numeric: "312" },
  GQ: { name: "Equatorial Guinea", numeric: "226" },
  GR: { name: "Greece", numeric: "300" },
  GS: { name: "South Georgia and the South Sandwich Islands", numeric: "239" },
  GT: { name: "Guatemala", numeric: "320" },
  GU: { name: "Guam", numeric: "316" },
  GW: { name: "Guinea-Bissau", numeric: "624" },
  GY: { name: "Guyana", numeric: "328" },
  HK: { name: "Hong Kong", numeric: "344" },
  HM: { name: "Heard Island and McDonald Islands", numeric: "334" },
  HN: { name: "Honduras", numeric: "340" },
  HR: { name: "Croatia", numeric: "191" },
  HT: { name: "Haiti", numeric: "332" },
  HU: { name: "Hungary", numeric: "348" },
  ID: { name: "Indonesia", numeric: "360" },
  IE: { name: "Ireland", numeric: "372" },
  IL: { name: "Israel", numeric: "376" },
  IM: { name: "Isle of Man", numeric: "833" },
  IN: { name: "India", numeric: "356" },
  IO: { name: "British Indian Ocean Territory", numeric: "86" },
  IQ: { name: "Iraq", numeric: "368" },
  IR: { name: "Iran, Islamic Republic of", numeric: "364" },
  IS: { name: "Iceland", numeric: "352" },
  IT: { name: "Italy", numeric: "380" },
  JE: { name: "Jersey", numeric: "832" },
  JM: { name: "Jamaica", numeric: "388" },
  JO: { name: "Jordan", numeric: "400" },
  JP: { name: "Japan", numeric: "392" },
  KE: { name: "Kenya", numeric: "404" },
  KG: { name: "Kyrgyzstan", numeric: "417" },
  KH: { name: "Cambodia", numeric: "116" },
  KI: { name: "Kiribati", numeric: "296" },
  KM: { name: "Comoros", numeric: "174" },
  KN: { name: "Saint Kitts and Nevis", numeric: "659" },
  KP: { name: "Korea, Democratic People's Republic of", numeric: "408" },
  KR: { name: "Korea, Republic of", numeric: "410" },
  KW: { name: "Kuwait", numeric: "414" },
  KY: { name: "Cayman Islands", numeric: "136" },
  KZ: { name: "Kazakhstan", numeric: "398" },
  LA: { name: "Lao People's Democratic Republic", numeric: "418" },
  LB: { name: "Lebanon", numeric: "422" },
  LC: { name: "Saint Lucia", numeric: "662" },
  LI: { name: "Liechtenstein", numeric: "438" },
  LK: { name: "Sri Lanka", numeric: "144" },
  LR: { name: "Liberia", numeric: "430" },
  LS: { name: "Lesotho", numeric: "426" },
  LT: { name: "Lithuania", numeric: "440" },
  LU: { name: "Luxembourg", numeric: "442" },
  LV: { name: "Latvia", numeric: "428" },
  LY: { name: "Libya", numeric: "434" },
  MA: { name: "Morocco", numeric: "504" },
  MC: { name: "Monaco", numeric: "492" },
  MD: { name: "Moldova, Republic of", numeric: "498" },
  ME: { name: "Montenegro", numeric: "499" },
  MF: { name: "Saint Martin (French part)", numeric: "663" },
  MG: { name: "Madagascar", numeric: "450" },
  MH: { name: "Marshall Islands", numeric: "584" },
  MK: { name: "North Macedonia", numeric: "807" },
  ML: { name: "Mali", numeric: "466" },
  MM: { name: "Myanmar", numeric: "104" },
  MN: { name: "Mongolia", numeric: "496" },
  MO: { name: "Macao", numeric: "446" },
  MP: { name: "Northern Mariana Islands", numeric: "580" },
  MQ: { name: "Martinique", numeric: "474" },
  MR: { name: "Mauritania", numeric: "478" },
  MS: { name: "Montserrat", numeric: "500" },
  MT: { name: "Malta", numeric: "470" },
  MU: { name: "Mauritius", numeric: "480" },
  MV: { name: "Maldives", numeric: "462" },
  MW: { name: "Malawi", numeric: "454" },
  MX: { name: "Mexico", numeric: "484" },
  MY: { name: "Malaysia", numeric: "458" },
  MZ: { name: "Mozambique", numeric: "508" },
  NA: { name: "Namibia", numeric: "516" },
  NC: { name: "New Caledonia", numeric: "540" },
  NE: { name: "Niger", numeric: "562" },
  NF: { name: "Norfolk Island", numeric: "574" },
  NG: { name: "Nigeria", numeric: "566" },
  NI: { name: "Nicaragua", numeric: "558" },
  NL: { name: "Netherlands, Kingdom of the", numeric: "528" },
  NO: { name: "Norway", numeric: "578" },
  NP: { name: "Nepal", numeric: "524" },
  NR: { name: "Nauru", numeric: "520" },
  NU: { name: "Niue", numeric: "570" },
  NZ: { name: "New Zealand", numeric: "554" },
  OM: { name: "Oman", numeric: "512" },
  PA: { name: "Panama", numeric: "591" },
  PE: { name: "Peru", numeric: "604" },
  PF: { name: "French Polynesia", numeric: "258" },
  PG: { name: "Papua New Guinea", numeric: "598" },
  PH: { name: "Philippines", numeric: "608" },
  PK: { name: "Pakistan", numeric: "586" },
  PL: { name: "Poland", numeric: "616" },
  PM: { name: "Saint Pierre and Miquelon", numeric: "666" },
  PN: { name: "Pitcairn", numeric: "612" },
  PR: { name: "Puerto Rico", numeric: "630" },
  PS: { name: "Palestine, State of", numeric: "275" },
  PT: { name: "Portugal", numeric: "620" },
  PW: { name: "Palau", numeric: "585" },
  PY: { name: "Paraguay", numeric: "600" },
  QA: { name: "Qatar", numeric: "634" },
  RE: { name: "Réunion", numeric: "638" },
  RO: { name: "Romania", numeric: "642" },
  RS: { name: "Serbia", numeric: "688" },
  RU: { name: "Russian Federation", numeric: "643" },
  RW: { name: "Rwanda", numeric: "646" },
  SA: { name: "Saudi Arabia", numeric: "682" },
  SB: { name: "Solomon Islands", numeric: "90" },
  SC: { name: "Seychelles", numeric: "690" },
  SD: { name: "Sudan", numeric: "729" },
  SE: { name: "Sweden", numeric: "752" },
  SG: { name: "Singapore", numeric: "702" },
  SH: { name: "Saint Helena, Ascension and Tristan da Cunha", numeric: "654" },
  SI: { name: "Slovenia", numeric: "705" },
  SJ: { name: "Svalbard and Jan Mayen", numeric: "744" },
  SK: { name: "Slovakia", numeric: "703" },
  SL: { name: "Sierra Leone", numeric: "694" },
  SM: { name: "San Marino", numeric: "674" },
  SN: { name: "Senegal", numeric: "686" },
  SO: { name: "Somalia", numeric: "706" },
  SR: { name: "Suriname", numeric: "740" },
  SS: { name: "South Sudan", numeric: "728" },
  ST: { name: "Sao Tome and Principe", numeric: "678" },
  SV: { name: "El Salvador", numeric: "222" },
  SX: { name: "Sint Maarten (Dutch part)", numeric: "534" },
  SY: { name: "Syrian Arab Republic", numeric: "760" },
  SZ: { name: "Eswatini", numeric: "748" },
  TC: { name: "Turks and Caicos Islands", numeric: "796" },
  TD: { name: "Chad", numeric: "148" },
  TF: { name: "French Southern Territories", numeric: "260" },
  TG: { name: "Togo", numeric: "768" },
  TH: { name: "Thailand", numeric: "764" },
  TJ: { name: "Tajikistan", numeric: "762" },
  TK: { name: "Tokelau", numeric: "772" },
  TL: { name: "Timor-Leste", numeric: "626" },
  TM: { name: "Turkmenistan", numeric: "795" },
  TN: { name: "Tunisia", numeric: "788" },
  TO: { name: "Tonga", numeric: "776" },
  TR: { name: "Türkiye", numeric: "792" },
  TT: { name: "Trinidad and Tobago", numeric: "780" },
  TV: { name: "Tuvalu", numeric: "798" },
  TW: { name: "Taiwan, Province of China", numeric: "158" },
  TZ: { name: "Tanzania, United Republic of", numeric: "834" },
  UA: { name: "Ukraine", numeric: "804" },
  UG: { name: "Uganda", numeric: "800" },
  UM: { name: "United States Minor Outlying Islands", numeric: "581" },
  US: { name: "United States of America", numeric: "840" },
  UY: { name: "Uruguay", numeric: "858" },
  UZ: { name: "Uzbekistan", numeric: "860" },
  VA: { name: "Holy See", numeric: "336" },
  VC: { name: "Saint Vincent and the Grenadines", numeric: "670" },
  VE: { name: "Venezuela, Bolivarian Republic of", numeric: "862" },
  VG: { name: "Virgin Islands (British)", numeric: "92" },
  VI: { name: "Virgin Islands (U.S.)", numeric: "850" },
  VN: { name: "Viet Nam", numeric: "704" },
  VU: { name: "Vanuatu", numeric: "548" },
  WF: { name: "Wallis and Futuna", numeric: "876" },
  WS: { name: "Samoa", numeric: "882" },
  YE: { name: "Yemen", numeric: "887" },
  YT: { name: "Mayotte", numeric: "175" },
  ZA: { name: "South Africa", numeric: "710" },
  ZM: { name: "Zambia", numeric: "894" },
  ZW: { name: "Zimbabwe", numeric: "716" },
};

/** Reverse lookup: world-atlas numeric id -> alpha-2 code. */
export const NUMERIC_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRIES).map(([a2, info]) => [info.numeric, a2]),
);

/** Human-readable country name for an alpha-2 code (falls back to the code). */
export function countryName(alpha2: string | null | undefined): string {
  if (!alpha2) return "Unknown";
  return COUNTRIES[alpha2.toUpperCase()]?.name ?? alpha2.toUpperCase();
}

/**
 * Flag emoji for an alpha-2 code, built from Unicode regional indicator symbols.
 * Returns a globe for unknown / non-country codes.
 */
export function countryFlag(alpha2: string | null | undefined): string {
  const code = alpha2?.toUpperCase();
  if (!code || code.length !== 2 || !/^[A-Z]{2}$/.test(code)) return "🌐";
  const A = 0x1f1e6;
  return String.fromCodePoint(
    A + (code.charCodeAt(0) - 65),
    A + (code.charCodeAt(1) - 65),
  );
}
